apiVersion: v1
kind: Service
metadata:
  name: {{ include "service_auth.fullname" . }}
  labels:
    {{- include "service_auth.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.portGrpc }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    {{- include "service_auth.selectorLabels" . | nindent 4 }}
