apiVersion: v2
name: gateway
description: A Helm chart for Kubernetes - Gateway component

dependencies:
  - name: kong
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 15.4.21
    alias: gateway-kong
    condition: gateway-kong.enabled

version: 0.1.0
appVersion: "1.16.0"
