basePath: /api
definitions:
  dto.AddAttendanceRequest:
    properties:
      company_id:
        type: string
      device_id:
        type: string
      employee_id:
        type: string
      face_image_url:
        type: string
      location_coordinates:
        type: string
      record_time:
        type: integer
      verification_method:
        type: string
      verification_score:
        maximum: 1
        minimum: 0
        type: number
    required:
    - company_id
    - device_id
    - employee_id
    - face_image_url
    - location_coordinates
    - record_time
    - verification_method
    - verification_score
    type: object
  dto.ErrResponseData:
    properties:
      code:
        description: Ma status code
        type: integer
      detail:
        description: Thong bao loi
      error:
        type: string
    type: object
  dto.GetAttendanceRecordsEmployeeRequest:
    properties:
      company_id:
        type: string
      employee_id:
        type: string
      page_size:
        type: integer
      page_stage:
        type: string
      year_month:
        description: 'Format: YYYY-MM'
        type: string
    required:
    - company_id
    - year_month
    type: object
  dto.GetAttendanceRecordsRequest:
    properties:
      company_id:
        type: string
      page_size:
        type: integer
      page_stage:
        type: string
      year_month:
        description: 'Format: YYYY-MM'
        type: string
    required:
    - company_id
    - year_month
    type: object
  dto.GetDailyAttendanceSummaryEmployeeRequest:
    properties:
      company_id:
        type: string
      employee_id:
        type: string
      page_size:
        type: integer
      page_stage:
        type: string
      summary_month:
        description: 'Format: YYYY-MM'
        type: string
    required:
    - company_id
    type: object
  dto.GetDailyAttendanceSummaryRequest:
    properties:
      company_id:
        type: string
      page_size:
        type: integer
      page_stage:
        type: string
      summary_month:
        description: 'Format: YYYY-MM'
        type: string
      work_date:
        description: Unix timestamp in milliseconds
        type: integer
    required:
    - company_id
    type: object
  dto.ResponseData:
    properties:
      code:
        description: Ma status code
        type: integer
      data:
        description: Du lieu duoc return
      message:
        description: Thong bao loi
        type: string
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8080
info:
  contact:
    email: lytranvinh.work@gmail.com
    name: API Support
    url: https://github.com/Youknow2509/
  description: This is a REST API for the Chat Service Auth.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Chat Service Auth REST API
  version: "1.0"
paths:
  /v1/attendance:
    post:
      consumes:
      - application/json
      description: Add attendance record
      parameters:
      - description: With the bearer started
        in: header
        name: Authorization
        required: true
        type: string
      - description: Request body add attendance record
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.AddAttendanceRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.ResponseData'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrResponseData'
      summary: Add attendance record
      tags:
      - Attendance
  /v1/attendance/records:
    post:
      consumes:
      - application/json
      description: Get attendance records
      parameters:
      - description: With the bearer started
        in: header
        name: Authorization
        required: true
        type: string
      - description: Request body get attendance records
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.GetAttendanceRecordsRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.ResponseData'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrResponseData'
      summary: Get attendance records
      tags:
      - Attendance
  /v1/attendance/records/employee:
    post:
      consumes:
      - application/json
      description: Get attendance records for employee
      parameters:
      - description: With the bearer started
        in: header
        name: Authorization
        required: true
        type: string
      - description: Request body get attendance records for employee
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.GetAttendanceRecordsEmployeeRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.ResponseData'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrResponseData'
      summary: Get attendance records for employee
      tags:
      - Attendance
  /v1/attendance/records/employee/summary/daily:
    post:
      consumes:
      - application/json
      description: Get daily attendance summary for employee
      parameters:
      - description: With the bearer started
        in: header
        name: Authorization
        required: true
        type: string
      - description: Request body get daily attendance summary for employee
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.GetDailyAttendanceSummaryEmployeeRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.ResponseData'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrResponseData'
      summary: Get daily attendance summary for employee
      tags:
      - Attendance
  /v1/attendance/records/summary/daily:
    post:
      consumes:
      - application/json
      description: Get daily attendance summary
      parameters:
      - description: With the bearer started
        in: header
        name: Authorization
        required: true
        type: string
      - description: Request body get daily attendance summary
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.GetDailyAttendanceSummaryRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.ResponseData'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrResponseData'
      summary: Get daily attendance summary
      tags:
      - Attendance
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
