basePath: /api
definitions:
  dto.CheckInRequest:
    properties:
      device_id:
        type: string
      face_image_url:
        type: string
      location:
        type: string
      timestamp:
        type: string
      user_id:
        type: string
      verification_method:
        type: string
      verification_score:
        type: number
    required:
    - device_id
    - face_image_url
    - location
    - timestamp
    - user_id
    - verification_method
    - verification_score
    type: object
  dto.CheckOutRequest:
    properties:
      device_id:
        type: string
      face_image_url:
        type: string
      location:
        type: string
      timestamp:
        type: string
      user_id:
        type: string
      verification_method:
        type: string
      verification_score:
        type: number
    required:
    - device_id
    - face_image_url
    - location
    - timestamp
    - user_id
    - verification_method
    - verification_score
    type: object
  dto.ErrResponseData:
    properties:
      code:
        description: Ma status code
        type: integer
      detail:
        description: Thong bao loi
      error:
        type: string
    type: object
  dto.GetAttendanceRecordsRequest:
    properties:
      company_id:
        type: string
      device_id:
        type: string
      end_date:
        type: string
      page:
        minimum: 1
        type: integer
      page_size:
        maximum: 100
        minimum: 1
        type: integer
      start_date:
        type: string
    type: object
  dto.GetMyAttendanceRecordsRequest:
    properties:
      end_date:
        type: string
      page:
        minimum: 1
        type: integer
      page_size:
        maximum: 100
        minimum: 1
        type: integer
      start_date:
        type: string
    type: object
  dto.ResponseData:
    properties:
      code:
        description: Ma status code
        type: integer
      data:
        description: Du lieu duoc return
      message:
        description: Thong bao loi
        type: string
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8080
info:
  contact:
    email: lytranvinh.work@gmail.com
    name: API Support
    url: https://github.com/Youknow2509/
  description: This is a REST API for the Chat Service Auth.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Chat Service Auth REST API
  version: "1.0"
paths:
  /v1/attendance/check_in:
    post:
      consumes:
      - application/json
      description: User check-in for attendance
      parameters:
      - description: Bearer token
        in: header
        name: authorization
        required: true
        type: string
      - description: Request body check-in
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.CheckInRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.ResponseData'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrResponseData'
      summary: Check In attendance
      tags:
      - Attendance
  /v1/attendance/check_out:
    post:
      consumes:
      - application/json
      description: User check-out for attendance
      parameters:
      - description: Bearer token
        in: header
        name: authorization
        required: true
        type: string
      - description: Request body check-out
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.CheckOutRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.ResponseData'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrResponseData'
      summary: Check Out attendance
      tags:
      - Attendance
  /v1/attendance/history/my:
    post:
      consumes:
      - application/json
      description: Retrieve the attendance history for the current user
      parameters:
      - description: Bearer token
        in: header
        name: authorization
        required: true
        type: string
      - description: Request body to get my attendance records
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/dto.GetMyAttendanceRecordsRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.ResponseData'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrResponseData'
      summary: Get My Attendance History
      tags:
      - Attendance
  /v1/attendance/records:
    post:
      consumes:
      - application/json
      description: Retrieve attendance records for device, day, user, ...
      parameters:
      - description: Bearer token
        in: header
        name: authorization
        required: true
        type: string
      - description: Request body to get attendance records
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/dto.GetAttendanceRecordsRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.ResponseData'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrResponseData'
      summary: Get Attendance Records
      tags:
      - Attendance
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
