basePath: /api
definitions:
  dto.CreateDeviceRequest:
    properties:
      address:
        maxLength: 255
        type: string
      company_id:
        type: string
      device_name:
        maxLength: 100
        minLength: 3
        type: string
      device_type:
        description: '0: FACE_TERMINAL, 1: MOBILE_APP, 2: WEB_CAMERA, 3: IOT_SENSOR'
        enum:
        - 0
        - 1
        - 2
        - 3
        type: integer
      location_id:
        type: string
      mac_address:
        type: string
      serial_number:
        maxLength: 100
        type: string
    required:
    - company_id
    - device_name
    type: object
  dto.ErrResponseData:
    properties:
      code:
        description: Ma status code
        type: integer
      detail:
        description: Thong bao loi
      error:
        type: string
    type: object
  dto.ResponseData:
    properties:
      code:
        description: Ma status code
        type: integer
      data:
        description: Du lieu duoc return
      message:
        description: Thong bao loi
        type: string
    type: object
  dto.UpdateDeviceRequest:
    properties:
      address:
        maxLength: 255
        type: string
      device_name:
        maxLength: 100
        minLength: 3
        type: string
      device_type:
        description: '0: FACE_TERMINAL, 1: MOBILE_APP, 2: WEB_CAMERA, 3: IOT_SENSOR'
        enum:
        - 0
        - 1
        - 2
        - 3
        type: integer
      location_id:
        type: string
      mac_address:
        type: string
      serial_number:
        maxLength: 100
        type: string
      status:
        description: '0: OFFLINE, 1: ONLINE, 2: MAINTENANCE, 3: ERROR'
        enum:
        - 0
        - 1
        - 2
        - 3
        type: integer
    type: object
  dto.UpdateInfoDeviceRequest:
    properties:
      device_id:
        type: string
      device_type:
        description: '0: FACE_TERMINAL, 1: MOBILE_APP, 2: WEB_CAMERA, 3: IOT_SENSOR'
        enum:
        - 0
        - 1
        - 2
        - 3
        type: integer
      mac_address:
        type: string
      serial_number:
        maxLength: 100
        type: string
    required:
    - device_id
    type: object
  dto.UpdateLocationDeviceRequest:
    properties:
      address:
        maxLength: 255
        type: string
      device_id:
        type: string
      location_id:
        type: string
    required:
    - address
    - device_id
    - location_id
    type: object
  dto.UpdateNameDeviceRequest:
    properties:
      device_id:
        type: string
      device_name:
        maxLength: 100
        minLength: 3
        type: string
    required:
    - device_id
    - device_name
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8080
info:
  contact:
    email: lytranvinh.work@gmail.com
    name: API Support
    url: https://github.com/Youknow2509/
  description: This is a REST API for the Chat Service Auth.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Chat Service Auth REST API
  version: "1.0"
paths:
  /v1/device:
    get:
      consumes:
      - application/json
      description: Get list of devices
      parameters:
      - description: Bearer <token>
        in: header
        name: authorization
        required: true
        type: string
      - description: Page number
        format: int
        in: query
        name: page
        type: string
      - description: Page size
        format: int
        in: query
        name: size
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.ResponseData'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrResponseData'
      summary: Get list of devices
      tags:
      - Core Device
    post:
      consumes:
      - application/json
      description: Create new device
      parameters:
      - description: Bearer <token>
        in: header
        name: authorization
        required: true
        type: string
      - description: Request body create device
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.CreateDeviceRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.ResponseData'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrResponseData'
      summary: Create new device
      tags:
      - Core Device
    put:
      consumes:
      - application/json
      description: Update device by ID
      parameters:
      - description: Bearer <token>
        in: header
        name: authorization
        required: true
        type: string
      - description: Request body update device
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.UpdateDeviceRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.ResponseData'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrResponseData'
      summary: Update device by ID
      tags:
      - Core Device
  /v1/device/{device_id}:
    delete:
      consumes:
      - application/json
      description: Delete device by ID
      parameters:
      - description: Bearer <token>
        in: header
        name: authorization
        required: true
        type: string
      - description: Device ID
        in: path
        name: device_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.ResponseData'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrResponseData'
      summary: Delete device by ID
      tags:
      - Core Device
    get:
      consumes:
      - application/json
      description: Delete device by ID
      parameters:
      - description: Bearer <token>
        in: header
        name: authorization
        required: true
        type: string
      - description: Device ID
        in: path
        name: device_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.ResponseData'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrResponseData'
      summary: Delete device by ID
      tags:
      - Core Device
  /v1/device/info:
    post:
      consumes:
      - application/json
      description: Update info device
      parameters:
      - description: Bearer <token>
        in: header
        name: authorization
        required: true
        type: string
      - description: Request body update device
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.UpdateInfoDeviceRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.ResponseData'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrResponseData'
      tags:
      - Core Device
  /v1/device/location:
    post:
      consumes:
      - application/json
      description: Update location
      parameters:
      - description: Bearer <token>
        in: header
        name: authorization
        required: true
        type: string
      - description: Request body update device
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.UpdateLocationDeviceRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.ResponseData'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrResponseData'
      summary: Update location
      tags:
      - Core Device
  /v1/device/name:
    post:
      consumes:
      - application/json
      description: Update name device
      parameters:
      - description: Bearer <token>
        in: header
        name: authorization
        required: true
        type: string
      - description: Request body update device
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.UpdateNameDeviceRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.ResponseData'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrResponseData'
      tags:
      - Core Device
  /v1/device/token/{device_id}:
    get:
      consumes:
      - application/json
      description: Get device access token
      parameters:
      - description: Bearer <token>
        in: header
        name: authorization
        required: true
        type: string
      - description: Device ID
        in: path
        name: device_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.ResponseData'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrResponseData'
      summary: Get device access token
      tags:
      - Core Device
  /v1/device/token/refresh/{device_id}:
    post:
      consumes:
      - application/json
      description: Refresh device access token
      parameters:
      - description: Bearer <token>
        in: header
        name: authorization
        required: true
        type: string
      - description: Device ID
        in: path
        name: device_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.ResponseData'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrResponseData'
      summary: Refresh device access token
      tags:
      - Core Device
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
