basePath: /api
definitions:
  dto.AddShiftEmployeeListReq:
    properties:
      company_id:
        type: string
      effective_from:
        type: integer
      effective_to:
        type: integer
      employee_ids:
        items:
          type: string
        type: array
      shift_id:
        type: string
    required:
    - company_id
    - effective_from
    - effective_to
    - employee_ids
    - shift_id
    type: object
  dto.AddShiftEmployeeReq:
    properties:
      effective_from:
        type: integer
      effective_to:
        type: integer
      employee_id:
        type: string
      shift_id:
        type: string
    required:
    - effective_from
    - effective_to
    - employee_id
    - shift_id
    type: object
  dto.ChangeStatusShiftReq:
    properties:
      company_id:
        type: string
      shift_id:
        type: string
      status:
        enum:
        - 0
        - 1
        type: integer
    required:
    - company_id
    - shift_id
    type: object
  dto.CreateShiftReq:
    properties:
      break_duration_minutes:
        type: integer
      company_id:
        type: string
      description:
        type: string
      early_departure_minutes:
        type: integer
      end_time:
        type: integer
      grace_period_minutes:
        type: integer
      name:
        type: string
      start_time:
        type: integer
      work_days:
        items:
          type: integer
        type: array
    required:
    - break_duration_minutes
    - company_id
    - early_departure_minutes
    - end_time
    - grace_period_minutes
    - name
    - start_time
    - work_days
    type: object
  dto.DeleteShiftUserReq:
    properties:
      employee_ids:
        items:
          type: string
        type: array
      shift_id:
        type: string
    required:
    - employee_ids
    - shift_id
    type: object
  dto.DisableShiftUserReq:
    properties:
      employee_id:
        type: string
      shift_id:
        type: string
    required:
    - employee_id
    - shift_id
    type: object
  dto.EditShiftReq:
    properties:
      break_duration_minutes:
        type: integer
      company_id:
        type: string
      description:
        type: string
      early_departure_minutes:
        type: integer
      end_time:
        type: integer
      grace_period_minutes:
        type: integer
      name:
        type: string
      shift_id:
        type: string
      start_time:
        type: integer
      work_days:
        items:
          type: integer
        type: array
    required:
    - break_duration_minutes
    - company_id
    - early_departure_minutes
    - end_time
    - grace_period_minutes
    - name
    - shift_id
    - start_time
    - work_days
    type: object
  dto.EnableShiftUserReq:
    properties:
      employee_id:
        type: string
      shift_id:
        type: string
    required:
    - employee_id
    - shift_id
    type: object
  dto.ErrResponseData:
    properties:
      code:
        description: Ma status code
        type: integer
      detail:
        description: Thong bao loi
      error:
        type: string
    type: object
  dto.GetInfoEmployeeDonotInShiftReq:
    properties:
      page:
        minimum: 1
        type: integer
      shift_id:
        type: string
    required:
    - shift_id
    type: object
  dto.GetInfoEmployeeInShiftReq:
    properties:
      page:
        minimum: 1
        type: integer
      shift_id:
        type: string
    required:
    - shift_id
    type: object
  dto.ResponseData:
    properties:
      code:
        description: Ma status code
        type: integer
      data:
        description: Du lieu duoc return
      message:
        description: Thong bao loi
        type: string
    type: object
  dto.ShiftEmployeeEditEffectiveDateReq:
    properties:
      employee_id:
        type: string
      new_effective_from:
        type: integer
      new_effective_to:
        type: integer
      shift_id:
        type: string
    required:
    - employee_id
    - new_effective_from
    - new_effective_to
    - shift_id
    type: object
  dto.ShiftEmployeeEffectiveDateReq:
    properties:
      effective_from:
        type: integer
      effective_to:
        type: integer
      page:
        type: integer
      size:
        type: integer
      user_id:
        type: string
    required:
    - effective_from
    - effective_to
    - page
    - size
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8080
info:
  contact:
    email: lytranvinh.work@gmail.com
    name: API Support
    url: https://github.com/Youknow2509/
  description: This is a REST API for the Chat Service Auth.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Chat Service Auth REST API
  version: "1.0"
paths:
  /v1/employee/shift:
    post:
      consumes:
      - application/json
      description: Get shift user effective date information for company
      parameters:
      - description: Bearer <token>
        in: header
        name: authorization
        required: true
        type: string
      - description: Get Shift For User With Effective Date Request
        in: body
        name: dto
        required: true
        schema:
          $ref: '#/definitions/dto.ShiftEmployeeEffectiveDateReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.ResponseData'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrResponseData'
      summary: Get shift user effective date information
      tags:
      - Shift
  /v1/employee/shift/add:
    post:
      consumes:
      - application/json
      description: Create shift information for company
      parameters:
      - description: Bearer <token>
        in: header
        name: authorization
        required: true
        type: string
      - description: Create Shift Request
        in: body
        name: dto
        required: true
        schema:
          $ref: '#/definitions/dto.AddShiftEmployeeReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.ResponseData'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrResponseData'
      summary: Create shift information
      tags:
      - Shift
  /v1/employee/shift/add/list:
    post:
      consumes:
      - application/json
      description: Add shift employee list for company
      parameters:
      - description: Bearer <token>
        in: header
        name: authorization
        required: true
        type: string
      - description: Add Shift Employee List Request
        in: body
        name: dto
        required: true
        schema:
          $ref: '#/definitions/dto.AddShiftEmployeeListReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.ResponseData'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrResponseData'
      summary: Add shift employee list
      tags:
      - Shift
  /v1/employee/shift/delete:
    post:
      consumes:
      - application/json
      description: Delete list shift employee information for company
      parameters:
      - description: Bearer <token>
        in: header
        name: authorization
        required: true
        type: string
      - description: Delete Shift User Request
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/dto.DeleteShiftUserReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.ResponseData'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrResponseData'
      summary: Delete list shift employee
      tags:
      - Shift
  /v1/employee/shift/disable:
    post:
      consumes:
      - application/json
      description: Disable shift for user information for company
      parameters:
      - description: Bearer <token>
        in: header
        name: authorization
        required: true
        type: string
      - description: Disable Shift For User Request
        in: body
        name: dto
        required: true
        schema:
          $ref: '#/definitions/dto.DisableShiftUserReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.ResponseData'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrResponseData'
      summary: Disable shift for user
      tags:
      - Shift
  /v1/employee/shift/enable:
    post:
      consumes:
      - application/json
      description: Enable shift for user information for company
      parameters:
      - description: Bearer <token>
        in: header
        name: authorization
        required: true
        type: string
      - description: Enable Shift For User Request
        in: body
        name: dto
        required: true
        schema:
          $ref: '#/definitions/dto.EnableShiftUserReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.ResponseData'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrResponseData'
      summary: Enable shift for user
      tags:
      - Shift
  /v1/employee/shift/in:
    post:
      consumes:
      - application/json
      description: Get info employee in shift for company
      parameters:
      - description: Bearer <token>
        in: header
        name: authorization
        required: true
        type: string
      - description: Get Info Employee In Shift Request
        in: body
        name: dto
        required: true
        schema:
          $ref: '#/definitions/dto.GetInfoEmployeeInShiftReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.ResponseData'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrResponseData'
      summary: Get info employee in shift
      tags:
      - Shift
  /v1/employee/shift/not_in:
    post:
      consumes:
      - application/json
      description: Get info employee donot in shift for company
      parameters:
      - description: Bearer <token>
        in: header
        name: authorization
        required: true
        type: string
      - description: Get Info Employee Donot In Shift Request
        in: body
        name: dto
        required: true
        schema:
          $ref: '#/definitions/dto.GetInfoEmployeeDonotInShiftReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.ResponseData'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrResponseData'
      summary: Get info employee donot in shift
      tags:
      - Shift
  /v1/shift:
    get:
      consumes:
      - application/json
      description: Get list shift information for company
      parameters:
      - description: Bearer <token>
        in: header
        name: authorization
        required: true
        type: string
      - description: Page number
        in: query
        name: page
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.ResponseData'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrResponseData'
      summary: Get list shift information
      tags:
      - Shift
    post:
      consumes:
      - application/json
      description: Create shift information for company
      parameters:
      - description: Bearer <token>
        in: header
        name: authorization
        required: true
        type: string
      - description: Create Shift Request
        in: body
        name: dto
        required: true
        schema:
          $ref: '#/definitions/dto.CreateShiftReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.ResponseData'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrResponseData'
      summary: Create shift information
      tags:
      - Shift
  /v1/shift/{id}:
    delete:
      consumes:
      - application/json
      description: Delete shift information for company
      parameters:
      - description: Bearer <token>
        in: header
        name: authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.ResponseData'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrResponseData'
      summary: Delete shift
      tags:
      - Shift
    get:
      consumes:
      - application/json
      description: Get shift detail information for company
      parameters:
      - description: Bearer <token>
        in: header
        name: authorization
        required: true
        type: string
      - description: Shift ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.ResponseData'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrResponseData'
      summary: Get shift detail information
      tags:
      - Shift
  /v1/shift/edit:
    post:
      consumes:
      - application/json
      description: Edit shift information for company
      parameters:
      - description: Bearer <token>
        in: header
        name: authorization
        required: true
        type: string
      - description: Edit Shift Request
        in: body
        name: dto
        required: true
        schema:
          $ref: '#/definitions/dto.EditShiftReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.ResponseData'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrResponseData'
      summary: Edit shift information
      tags:
      - Shift
  /v1/shift/status:
    post:
      consumes:
      - application/json
      description: Change status shift information for company
      parameters:
      - description: Bearer <token>
        in: header
        name: authorization
        required: true
        type: string
      - description: Change Status Shift Request
        in: body
        name: dto
        required: true
        schema:
          $ref: '#/definitions/dto.ChangeStatusShiftReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.ResponseData'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrResponseData'
      summary: Change status shift
      tags:
      - Shift
  /v1/user/edit/effective:
    post:
      consumes:
      - application/json
      description: Edit shift employee effective date information
      parameters:
      - description: Bearer <token>
        in: header
        name: authorization
        required: true
        type: string
      - description: Edit Shift Request
        in: body
        name: dto
        required: true
        schema:
          $ref: '#/definitions/dto.ShiftEmployeeEditEffectiveDateReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.ResponseData'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrResponseData'
      summary: Edit shift employee effective date information
      tags:
      - Shift
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
