basePath: /api
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8080
info:
  contact:
    email: lytranvinh.work@gmail.com
    name: API Support
    url: https://github.com/Youknow2509/
  description: This is a REST API for the Chat Service Auth.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Chat Service Auth REST API
  version: "1.0"
paths: {}
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
